name: Run Solidity tests and coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests_and_coverate:
    name: Run all tests and coverage
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Running tests and coverage
        run: yarn coverage
